services:
   postgres:
      image: postgres
      container_name: postgres14
      ports:
         - 6500:5432
      env_file:
         - ./app.env
      volumes:
         - postgres_data:/var/lib/postgresql/data
volumes:
   postgres_data:
